[package]
name = "term_input_macros"
version = "0.2.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
indexmap = "2.7.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
