before_install:
  - >
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            sudo apt-get update -qq;
            sudo apt-get install -y libdbus-1-dev;
      fi
  - rustup component add rustfmt

language: rust

rust:
  - nightly

os:
  - linux
  - osx

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - (cd tiny && cargo build --no-default-features --features tls-rustls)
  - cargo fmt --all -- --check
