[package]
name = "tiny"
version = "0.4.2"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
repository = "https://github.com/osa1/tiny"
readme = "README.md"
license = "MIT"
keywords = ["irc"]
categories = ["network-programming"]
description = "An IRC client"

[badges]
travis-ci = { repository = "osa1/tiny" }

[lib]
name = "tiny"
path = "src/lib.rs"

[[bin]]
name = "tiny"
path = "bin/main.rs"

[dependencies]
base64 = "0.6.0"
libc = "0.2.22"
mio = "0.6.9"
native-tls = "0.1.4"
net2 = "0.2.23"
notify-rust = "3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_yaml = "0.7.1"
take_mut = "0.2.0"
term_input = "0.1.4"
termbox_simple = "0.2.1"
time = "0.1"

[dev-dependencies]
quickcheck = "0.3"

[profile.release]
lto = true
