[package]
name = "libtiny_ui"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Defines the interface for the UI implementations for tiny"
edition = "2018"

[dependencies]
objekt = "0.1"
time = "0.1"
