[package]
name = "libtiny_client"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "An IRC client library, mainly to be used in tiny"
edition = "2018"

[dependencies]
base64 = "0.6.0"
env_logger = "0.7"
futures-preview = { version = "0.3.0-alpha.19",  features = ["async-await"] }
futures-util-preview = "0.3.0-alpha.19"
libtiny_logger = { path = "../libtiny_logger" }
libtiny_wire = { path = "../libtiny_wire" }
log = "0.4"
native-tls = "0.2"
tokio = { git = "https://github.com/tokio-rs/tokio.git", features = ["timer"], rev = "227533d" }
tokio-executor = { git = "https://github.com/tokio-rs/tokio.git", rev = "227533d" }
tokio-tls = { git = "https://github.com/tokio-rs/tokio.git", rev = "227533d" }
