[package]
name = "termbox_simple"
version = "0.2.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
links = "termbox_simple"
description = "A hacked version of termbox (see README)"
repository = "https://github.com/osa1/tiny"
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3.35"

[dev-dependencies]
mio = "0.6.9"
term_input = "0.1.2"
