[package]
name = "term_input"
version = "0.1.5"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Input handling for xterm-compatible terminals"
repository = "https://github.com/osa1/tiny"
license = "MIT"
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.18"
libc = "0.2"
mio = "0.6"
tokio = { git = "https://github.com/tokio-rs/tokio.git", rev = "227533d" }
