[package]
name = "term_input"
version = "0.1.1"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Input handling for xterm-compatible terminals"
repository = "https://github.com/osa1/tiny"
license = "MIT"

[dependencies]
libc = "0.2"
nix = "0.7"

[dev-dependencies]
mio = "0.6.9"
